### ISSUE TITLE
Suggestion: Is there some better workflow?

### ISSUE THREAD

**Issue by vladaman** [Tienisto/flutter-fast-i18n#15]
Hi,

I wonder if there is better way to add keys and rebuild project. My current setup with 6 languages is such:

1. add a key to strings.i18n.json manually
2. add same key into remaining nto strings_**.i18n.json (annoying and repetitive task)
3. run flutter pub run fast_i18n
4. finally I can use the string  
5. rinse & repeat for next string

This is just too time consuming, because first, I cannot use string unless it's in all translation files, otherwise the project will not build. Second, running flutter run pub fast_i18n is again manual step - can this be automated with auto-reload?

**Comment by Tienisto** [comment]
Thanks for this issue.
I only maintain projects with max. 3 languages so it was not that annoying to me :)

Currently, I have 2 ideas:
- an option to make it optionally to translate to every language
- a watch utility command like `flutter pub run fast_i18n watch`

Does this sound good to you? Or do you have further ideas?

**Comment by Tienisto** [comment]
I just released both features in `4.8.0`. You can try it out.
