### ISSUE TITLE
How to change language from view model

### ISSUE THREAD

**Issue by sadabwasim** [Tienisto/flutter-fast-i18n#2]
Hi @Tienisto,
Thanks for making this amazing library, I want to update the language for the whole app from the settings page. 
I used LocaleSettings.setLocale('es'); in main page and it's working fine.
But I'm using MVVM architecture and I want to change the language from my view-model any suggestions from your side.

**Comment by Tienisto** [comment]
A workaround would be to store the `changeLocale(locale)` function into a global variable. Then call it from anywere.
It is quite dirty but it should work:

```dart
// globals.dart
class Globals {
  static Function changeLocale;
}


// in your main state
void changeLocale(String locale) {
  setState(() {
    LocaleSettings.setLocale(locale);
  });
}

@override
void initState() {
  super.initState();
  Globals.changeLocale = this;
}

// in your child widget
setState(() {
  Globals.changeLocale('es');
});
```

**Comment by MDSADABWASIM** [comment]
I think it should be more sufficient than this, what if I have lots lf stateless widgets?

**Comment by Tienisto** [comment]
Please give me feedback about new version `1.8.1`.

First wrap your app with `TranslationProvider`, e.g. `runApp(TranslationProvider(child: MyApp()));`

Then use `Translations.of(context)` to get the `t` variable:
```dart
final t = Translations.of(context); // reacts to locale changes and forces a re-render of the widget
String translated = t.someKey.anotherKey;
```

**Comment by sadabwasim** [comment]
Sure will do that, thanks for amazing support.
