### ISSUE TITLE
fix lint hint "Private field could be final"

### ISSUE THREAD

**Issue by boskokg** [Tienisto/flutter-fast-i18n#20]
I am attaching the image of the hint that lint reports for the generated file.

![Screenshot 2021-07-11 at 03 30 37](https://user-images.githubusercontent.com/18428281/125188205-91d92c00-e1f8-11eb-86fb-0a294be0ad02.png)

**Comment by Tienisto** [comment]
Thanks for this issue. I will fix that!

**Comment by Tienisto** [comment]
Added in 4.11.0
