### ISSUE TITLE
fix lint hint "Avoid using braces in interpolation when not needed"

### ISSUE THREAD

**Issue by boskokg** [Tienisto/flutter-fast-i18n#21]
I am attaching the image of the hint that lint reports for the generated file.

![Screenshot 2021-07-11 at 03 34 49](https://user-images.githubusercontent.com/18428281/125188382-42dfc680-e1f9-11eb-80b2-e9f3896c48ca.png)

**Comment by Tienisto** [comment]
Added in 4.11.0
