### ISSUE TITLE
lint hint "DO use curly braces for all flow control structures"

### ISSUE THREAD

**Issue by boskokg** [Tienisto/flutter-fast-i18n#23]
I am attaching the image of the hint:

![Screenshot 2021-07-14 at 03 22 47](https://user-images.githubusercontent.com/18428281/125589236-6fdb1865-a4aa-4584-b07d-5bc3239746f5.png)

![Screenshot 2021-07-14 at 03 32 43](https://user-images.githubusercontent.com/18428281/125590496-43da1ee1-2cba-4400-8634-3186886dbb42.png)

![Screenshot 2021-07-14 at 03 33 23](https://user-images.githubusercontent.com/18428281/125590595-391636b2-074d-44f6-8f17-38f218f7bad6.png)

**Comment by Tienisto** [comment]
Fixed in `5.0.0`
