### ISSUE TITLE
lint hint "The declaration '_missingPluralResolver' isn't referenced"

### ISSUE THREAD

**Issue by boskokg** [Tienisto/flutter-fast-i18n#26]
Not sure if this code should be removed but please check. I am attaching the image:

![Screenshot 2021-07-14 at 03 29 03](https://user-images.githubusercontent.com/18428281/125590021-cf830014-3afc-440a-b368-0f84a366804a.png)

**Comment by Tienisto** [comment]
Well, I can fix that also.
But keep in mind that generated dart usually should **not** be tracked by the dart analyser.

**Comment by boskokg** [comment]
Thank you @Tienisto 

Thing is that I can only ignore the entire file but thing is that there are things in the generated file that is good to be reported (an example is an extra translation not available in the main translation that is reported as an invalid override). So I find it good to have this generated file as not ignored

**Comment by boskokg** [comment]
btw thanks a lot for such a great plugin!

**Comment by Tienisto** [comment]
Fixed in `5.0.0`
