### ISSUE TITLE
Key with multy digit number wrong generation

### ISSUE THREAD

**Issue by boskokg** [Tienisto/flutter-fast-i18n#29]
Note: key_case is snake.
Example is key in json "toast_cycle_alert_30_min" and get method is named as "toast_cycle_alert_3_0_min"

**Comment by Tienisto** [comment]
I just add the fix to master. Will release soon.

Out of curiosity, why do you use `key_case: snake` when your key is already in snake case?

**Comment by boskokg** [comment]
Thanks @Tienisto !

what key_case should I use?

**Comment by Tienisto** [comment]
You can leave out this configuration, or set it explicitly to `key_case: null`

**Comment by boskokg** [comment]
Thank you! I didn't know about the null :-)
