### ISSUE TITLE
In and out files location config

### ISSUE THREAD

**Issue by DenchikBY** [Tienisto/flutter-fast-i18n#3]
Hi, thanks for your package, it's awesome!)

But it would be great if we will have possibility to set in and out file directories and in files regex.
For example in my case I store my locale files in assets/locale and them have names {languageName}.json
I think it's not logical to mix them with code files in lib directory because it's assets.

So it would be nice if I could set in dir => assets/locale, out dir => lib/i18n and files pattern => **.json

Btw also I think dependency of `devicelocale` is reduntant because it haven't implementation for flutter desktop, but can be checked easy just like that
`final locale = WidgetsBinding.instance.window.locale;`

**Comment by Tienisto** [comment]
I will check if I can leave out the `devicelocale` dependency, thanks for your feedback.
Regarding setting in and out locations: The `build` API is quite cumbersome, I will probably have to look for another code generation library.
