### ISSUE TITLE
build.yaml | Schema validation: Property 'targets' is not allowed

### ISSUE THREAD

**Issue by boskokg** [Tienisto/flutter-fast-i18n#31]
Can you please explain why do I get this warning?

![Screenshot 2021-07-17 at 03 19 53](https://user-images.githubusercontent.com/18428281/126030946-450d606e-5217-46b8-9c24-1212b111b8aa.png)

**Comment by Tienisto** [comment]
This seems to be an issue of Flutter / build_runner. I also get this warning in my projects.
`targets` is a normal keyword.

https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md
https://moor.simonbinder.eu/docs/advanced-features/builder_options/
