### ISSUE TITLE
'in' can't be used as an identifier because it's a keyword.

### ISSUE THREAD

**Issue by ffshy1214** [Tienisto/flutter-fast-i18n#32]
iso 3166 country code of India have problem, as below: 

![Screen Shot 2021-07-28 at 9 39 51 AM](https://user-images.githubusercontent.com/32861271/127250689-1b310918-9b88-4944-aa15-e7c47f94c225.png)

**Comment by Tienisto** [comment]
Thanks for this issue. I will probably add a rename from `in` to `indian`

**Comment by Tienisto** [comment]
By the way, it is more common to use language codes. Or language code + country code. Using country code only is pretty rare

**Comment by Tienisto** [comment]
Fixed in `5.0.3`.

**Comment by ffshy1214** [comment]
> By the way, it is more common to use language codes. Or language code + country code. Using country code only is pretty rare.
> Also be aware that country codes must be in uppercase, e.g. `CN` not `cn`. Otherwise it is interpreted as language code like `zh` of `zh-Hant-TW`

Thanks a lot for the quick response, and We'll consider your suggestion. Thanks
