### ISSUE TITLE
QOL: Change the "Built on" date only if the translations have actually been changed

### ISSUE THREAD

**Issue by Curvel** [Tienisto/flutter-fast-i18n#48]
**Motivation**
I use several packages that depend on code generation. So I have to run the code generation quite often. And each time the timestamp in the `strings.g.dart` updates. I then have to revert that file, because at first glance in the git log it looks like the localization has changed, even though nothing has changed.

So it would be a nice QOL improvement :)

**Comment by Tienisto** [comment]
Hi,

I would add an option to disable the timestamp, especially with #49, reading the generated file seems a little bit too complicated to me :)

**Comment by Tienisto** [comment]
You can disable timestamps in `5.7.0` now.

**Comment by Curvel** [comment]
Thanks!
