### ISSUE TITLE
Change "t" access variable

### ISSUE THREAD

**Issue by SchrodingersGat** [Tienisto/flutter-fast-i18n#5]
Is it possible to change (or customize) the "t" access variable? e.g. `t.my.string.path` becomes `i18n.my.string.path`?

**Comment by Tienisto** [comment]
Not yet, but nice idea. Will implement that in the next release!

**Comment by Tienisto** [comment]
You can customize this variable now in version `2.2.0`.
Just set the `output_translate_var` in `build.yaml` to your desired variable name.
For more information checkout the updated README file
