### ISSUE TITLE
Does not support pure Dart packages

### ISSUE THREAD

**Issue by fzyzcjy** [Tienisto/flutter-fast-i18n#61]
Hi thanks for the code generator! However, I need it in pure Dart packages (as well as Flutter packages), but the generator generates code with `import 'package:flutter/widgets.dart';`, which is impossible for dart packages.

Talking about #63, maybe we can create two supportive packages (instead of one), one for dart, one for flutter-specific features.

**Comment by Tienisto** [comment]
There is a flag `locale_handling: false` to disable generation of `LocaleSettings` and other wrappers.
Maybe we can add a `dart_only: true` flag which is basically the same as `locale_handling: false` but also removes some util functions which need flutter

**Comment by fzyzcjy** [comment]
I am currently trying to refactor things into dart package and flutter package. Then for, say, a `my_library` pure-dart package, both pure-Dart packages and Flutter packages can use it happily. The pure-Dart consumers will only use dart-related apis, while the Flutter consumers will enjoy extra Flutter-related apis.
