### ISSUE TITLE
Linter errors such as "Missing type arguments for map literal."

### ISSUE THREAD

**Issue by fzyzcjy** [Tienisto/flutter-fast-i18n#64]
## 1.

![image](https://user-images.githubusercontent.com/5236035/165470290-bc23b174-0f4f-4045-a400-86596a4be111.png)

Missing type arguments for map literal.  Try adding an explicit type, or remove implicit-dynamic from your analysis options file.

Solution is quite simple: Change it to

```
extension on _StringsEn {
  Map<String, dynamic> _buildFlatMap() {
    return <String, dynamic>{
...
    };
  }
}
```

## 2.

  late final Map<String, dynamic> _flatMap = _buildFlatMap();

Has

Annotate overridden members.

## 3.

```
  // ignore: unused_field
  @override
  final _StringsEn _root;
```

still has unused_field warning, because the "//ignore" is *not* placed *directly* above the line of "_root" variable.

**Comment by Tienisto** [comment]
Fixed in master
