### ISSUE TITLE
Help: Can not find build.yaml

### ISSUE THREAD

**Issue by FantaZZ** [Tienisto/flutter-fast-i18n#71]
Simply demo.  Did I miss something ?

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/5322276/166200485-307c99e1-d115-43b9-94be-54796473f2cb.png">

**Comment by FantaZZ** [comment]
Oh I find, ```option```

**Comment by Tienisto** [comment]
This is the `build.yaml` structure used by `build_runner` and therefore by many libraries :)
